server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
        thymeleaf:    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:#      content-type: text/html
    
      
